require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'GiantPlay' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-google-cast', :path => '../node_modules/react-native-google-cast'

  pod 'toolbar-android', :path => '../node_modules/@react-native-community/toolbar-android'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'GiantPlayTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GiantPlay-tvOS' do
  # Pods for GiantPlay-tvOS

  target 'GiantPlay-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
